[package]
name = "mmv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.5.17", features = ["derive"]}
glob = "0.3.1"
regex = "1.10.2"
tempfile = "3.8.0"